services:
    laravel:
        build:
            context: ./docker/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1001}'
                NODE_VERSION: '${NODE_VERSION:-22}'
        image: 'app-8.4-fpm'
        container_name: laravel-app
        environment:
            WWWUSER: '${WWWUSER:-1001}'
            LARAVEL_SAIL: 1
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            APP_ENV: '${APP_ENV:-production}'
            APP_DEBUG: '${APP_DEBUG:-false}'
        user: ${UID:-1001}:${GID:-1001}
        volumes:
            - .:/var/www/html
            - ./docker/8.4/php.ini:/etc/php/8.4/fpm/conf.d/99-custom.ini:ro
            - ./docker/8.4/php.ini:/etc/php/8.4/cli/conf.d/99-custom.ini:ro
        depends_on:
            - mysql
        networks:
            - kanboard
        restart: unless-stopped

    nginx:
        image: 'nginx:alpine'
        container_name: nginx-server
        volumes:
            - .:/var/www/html:ro
            - ./docker/8.4/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - laravel
        networks:
            - kanboard
        restart: unless-stopped

    mysql:
        image: 'mysql:8.0'
        container_name: mysql-db
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - kanboard-mysql:/var/lib/mysql
        networks:
            - kanboard
        restart: unless-stopped

    phpmyadmin:
        image: 'phpmyadmin:5.2'
        ports:
            - '8888:80'
        environment:
            PMA_HOST: mysql
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
            UPLOAD_LIMIT: '512M'
        depends_on:
            - mysql
        networks:
            - kanboard
        restart: unless-stopped

volumes:
    kanboard-mysql:
        driver: local

networks:
    kanboard:
        driver: bridge
